name: Docker Build and Test

on:
  push:
    branches: [ "main", "feature/**" ]
    paths:
      - '**.Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker-test.yml'
      - 'src/**'
      - 'requirements.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/docker-test.yml'
      - 'src/**'
      - 'requirements.txt'

jobs:
  test-individual-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-file: ['ollama.Dockerfile', 'streamlit.Dockerfile']
        include:
          - docker-file: 'ollama.Dockerfile'
            image-name: 'resume_experience_ollama'
            health-check-port: 11434
          - docker-file: 'streamlit.Dockerfile'
            image-name: 'resume_experience_streamlit'
            health-check-port: 8501

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.docker-file }}
          tags: ${{ matrix.image-name }}:test
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test container startup
        env:
          OLLAMA_BASE_URL: http://localhost:11434
        run: |
          docker run --gpus all -d --name test-container -p ${{ matrix.health-check-port }}:${{ matrix.health-check-port }} ${{ matrix.image-name }}:test
          # Wait for container to start
          sleep 30
          # Check container is running
          docker ps | grep test-container
          # Check logs for any errors
          docker logs test-container
          # Test health check endpoint
          curl --fail http://localhost:${{ matrix.health-check-port }} || curl --fail http://localhost:${{ matrix.health-check-port }}/_stcore/health

      - name: Cleanup
        if: always()
        run: docker rm -f test-container || true

  test-docker-compose:
    needs: test-individual-builds
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start containers with docker-compose
        run: |
          docker-compose up -d --build
          sleep 45  # Give containers time to start up properly

      - name: Check containers status
        run: |
          docker-compose ps
          docker-compose logs

      - name: Test services health
        run: |
          # Test Ollama service
          curl --fail http://localhost:11434 || exit 1
          # Test Streamlit service
          curl --fail http://localhost:8501/_stcore/health || exit 1

      - name: Cleanup
        if: always()
        run: docker-compose down -v