name: Deploy Streamlit App

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    
    - name: Install shell dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils
        sudo apt-get install -y tesseract-ocr

    - name: Run Tests
      run: |
        source venv/bin/activate
        cd src
        python -m pytest

    - name: Deploy Streamlit
      run: |
        source venv/bin/activate
        nohup streamlit run Predict_prior_experience.py &
